;;;
;;;   Derived from ``Sample/devquery.c'' in NI-488.2 package.
;;;
(use ni4882)
(use gauche.uvector)

(define debug? #t)
(define (p x)  (if debug? (print x)))

(define (sta)  (format #f "0x~4,'0x" (Ibsta)))
(define (ck ib)
  (p #"~|ib|=~(sta)")
  (if (not (zero? (logand (Ibsta) ERR)))
    (GpibError #"~|ib| Error")))

(define dev   #f)
(define board #f)

(define (devquery pad sad)

  (let ((buf (make-u8vector 256 0)))

    (set! dev (ibdev board pad sad T10s 1 0))
    (if (= dev -1)
      (GpibError "ibdev Error"))

    (ibclr dev)
    (ck "(ibclr)")

    (ibwrt dev (string->u8vector "*IDN?"))
    (ck "(ibwrt)")

    (ibrd dev buf)
    (ck "(ibrd)")
    #;(print buf)
    (u8vector-set! buf (Ibcnt) 0)
    (let ((t (- (Ibcnt) 1)))
      (if (= #x0a (u8vector-ref buf t))
        (u8vector-set! buf t 0)))
    (print #"~|pad|: \"~(u8vector->string buf)\"")

    (ibonl dev 0)
    (ck "(ibonl)")
    0))

(define (GpibError msg)
  (let ((Status (Ibsta))
        (Error  (Iberr))
        (Count  (Ibcnt)))
    (print msg)
    (format #t "ibsta = 0x~2,'0X  <" Status)
    (display (if (not (zero? (logand Status ERR)))  " ERR"   ""))
    (display (if (not (zero? (logand Status TIMO))) " TIMO"  ""))
    (display (if (not (zero? (logand Status END)))  " END"   ""))
    (display (if (not (zero? (logand Status SRQI))) " SRQI"  ""))
    (display (if (not (zero? (logand Status RQS)))  " RQS"   ""))
    (display (if (not (zero? (logand Status CMPL))) " CMPL"  ""))
    (display (if (not (zero? (logand Status LOK)))  " LOK"   ""))
    (display (if (not (zero? (logand Status REM)))  " REM"   ""))
    (display (if (not (zero? (logand Status CIC)))  " CIC"   ""))
    (display (if (not (zero? (logand Status ATN)))  " ATN"   ""))
    (display (if (not (zero? (logand Status TACS))) " TACS"  ""))
    (display (if (not (zero? (logand Status LACS))) " LACS"  ""))
    (display (if (not (zero? (logand Status DTAS))) " DTAS"  ""))
    (display (if (not (zero? (logand Status DCAS))) " DCAS"  ""))
    (print " >")
    (format #t "iberr = ~d" Error)
    (print
     (cond
       ((= Error EDVR) " EDVR <Driver error>")
       ((= Error ECIC) " ECIC <Not Controller-In-Charge>")
       ((= Error ENOL) " ENOL <No Listener>")
       ((= Error EADR) " EADR <Address error>")
       ((= Error EARG) " EARG <Invalid argument>")
       ((= Error ESAC) " ESAC <Not System Controller>")
       ((= Error EABO) " EABO <Operation aborted>")
       ((= Error ENEB) " ENEB <No GPIB board>")
       ((= Error EDMA) " EDMA <DMA error>")
       ((= Error EOIP) " EOIP <Async I/O in progress>")
       ((= Error ECAP) " ECAP <No capability>")
       ((= Error EFSO) " EFSO <File system error>")
       ((= Error EBUS) " EBUS <Command error>")
       ((= Error ESRQ) " ESRQ <SRQ stuck on>")
       ((= Error ETAB) " ETAB <Table Overflow>")
       ((= Error ELCK) " ELCK <Interface is locked>")
       ((= Error EARM) " EARM <ibnotify callback failed to rearm>")
       ((= Error EHDL) " EHDL <Input handle is invalid>")
       ((= Error EWIP) " EWIP <Wait in progress on specified input handle>")
       ((= Error ERST) " ERST <The event notification was cancelled due to a reset of the interface>")
       ((= Error EPWR) " EPWR <The interface lost power>")
       (else   " Unknown error")))
    (format  #t "ibcnt = ~d~%" Count)
    (ibonl dev 0)
    (exit 1)))

(define (main args)
  (set! board 0)
  (if (= (length args) 2)
    (let ((pad (string->number (list-ref args 1))))
      (devquery pad 0))
    1))

;; EOF
